### datasource
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/api1seap
#spring.datasource.username=mfkldev
#spring.datasource.password=root
#spring.datasource.initialization-mode=always
#spring.datasource.data=classpath:data.sql
#
## jpa
#spring.jpa.generate-ddl=true
##create
#spring.jpa.hibernate.ddl-auto=update
spring:
  profiles:
    active:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect